src/chapter6/beans/UserComment.java
package chapter6.beans;

import java.io.Serializable;
import java.util.Date;

public class UserComment implements Serializable{

	//プロパティ
	private int id;
	private String account;
	private String name;
	private int userId;
	private int messageId;
	private String text;
	private Date created_date;

	//setter
	public void setId(int id) {
    	this.id = id;
    }
    public void setAccount(String account) {
    	this.account = account;
    }
    public void setName(String name) {
    	this.name = name;
    }
    public void setUserId(int userId) {
    	this.userId = userId;
    }
    public void setMessageId(int messageId) {
    	this.messageId = messageId;
    }
    public void setText(String text) {
    	this.text = text;
    }
    public void setCreated_Date(Date created_date) {
    	this.created_date = created_date;
    }

    //getter
    public int getId() {
    	return this.id;
    }
    public String getAccount() {
    	return this.account;
    }
    public String getName() {
    	return this.name;
    }
    public int getUserId() {
    	return this.userId;
    }
    public int getMessageId() {
    	return this.messageId;
    }
    public String getText() {
    	return this.text;
    }
    public Date getCreated_Date() {
    	return this.created_date;
    }
}

src/chapter6/controller/EditServlet.java
package chapter6.controller;


import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.Message;
import chapter6.service.MessageService;

@WebServlet(urlPatterns = {"/edit"})

public class EditServlet extends HttpServlet {

	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException {

		HttpSession session = request.getSession();
		String messageId = request.getParameter("messageId");
		Message message =  new MessageService().editSelect(messageId);
		List<String> errorMessages = new ArrayList<String>();

		if(!(messageId.matches("[0-9]+")) || message == null) {
			errorMessages.add("不正なパラメータが入力されました");
			session.setAttribute("errorMessages",errorMessages);
			response.sendRedirect("./");
			return;
		}

		request.setAttribute("message", message);//値を保持
		request.getRequestDispatcher("edit.jsp").forward(request, response);//Editページへの遷移を指定
	}


	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response)//Editjspから更新したメッセージを受け取る
			throws IOException, ServletException {

		List<String> errorMessages = new ArrayList<String>();
		Message message = getMessage(request);
		if (!isValid(message, errorMessages) ) {
			request.setAttribute("errorMessages", errorMessages);
			request.setAttribute("message", message);
			request.getRequestDispatcher("edit.jsp").forward(request, response);
			return;
		}

		new MessageService().update(message);

		response.sendRedirect("./");
	}

	private Message getMessage(HttpServletRequest request) throws IOException, ServletException {
        Message message = new  Message();
        message.setId(Integer.parseInt(request.getParameter("id")));
        message.setText(request.getParameter("text"));
        return message;
	}

	private boolean isValid(Message message, List<String> errorMessages) {
		String newtext = message.getText();

		if (!StringUtils.isBlank(newtext) && (140 < newtext.length())) {
			errorMessages.add("つぶやきは140文字以下で入力してください");
		}
		if (StringUtils.isBlank(newtext)) {
			errorMessages.add("つぶやきを入力してください");
		}
		if (errorMessages.size() != 0) {
			return false;
		}
		return true;
	}
}

src/chapter6/controller/LoginServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter6.beans.User;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        String accountOrEmail = request.getParameter("accountOrEmail");
        String password = request.getParameter("password");

        User user = new UserService().select(accountOrEmail, password);
        if (user == null) {
            List<String> errorMessages = new ArrayList<String>();
            errorMessages.add("ログインに失敗しました");
            request.setAttribute("errorMessages", errorMessages);
            request.getRequestDispatcher("login.jsp").forward(request, response);
            return;
        }

        HttpSession session = request.getSession();
        session.setAttribute("loginUser", user);
        response.sendRedirect("./");
    }
}

src/chapter6/controller/SettingServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
import chapter6.exception.NoRowsUpdatedRuntimeException;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/setting" })
public class SettingServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession();
        User loginUser = (User) session.getAttribute("loginUser");

        User user = new UserService().select(loginUser.getId());

        request.setAttribute("user", user);
        request.getRequestDispatcher("setting.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession();
        List<String> errorMessages = new ArrayList<String>();

        User user = getUser(request);
        if (isValid(user, errorMessages)) {
            try {
                new UserService().update(user);
            } catch (NoRowsUpdatedRuntimeException e) {
                errorMessages.add("他の人によって更新されています。最新のデータを表示しました。データを確認してください。");
            }
        }

        if (errorMessages.size() != 0) {
            request.setAttribute("errorMessages", errorMessages);
            request.setAttribute("user", user);
            request.getRequestDispatcher("setting.jsp").forward(request, response);
            return;
        }

        session.setAttribute("loginUser", user);
        response.sendRedirect("./");
    }

    private User getUser(HttpServletRequest request) throws IOException, ServletException {

        User user = new User();
        user.setId(Integer.parseInt(request.getParameter("id")));
        user.setName(request.getParameter("name"));
        user.setAccount(request.getParameter("account"));
        user.setPassword(request.getParameter("password"));
        user.setEmail(request.getParameter("email"));
        user.setDescription(request.getParameter("description"));
        return user;
    }

    private boolean isValid(User user, List<String> errorMessages) {

    	int id = user.getId();
        String name = user.getName();
        String account = user.getAccount();
        String email = user.getEmail();

        User accountMatchUser = new UserService().select(account);

        if (!StringUtils.isEmpty(name) && (20 < name.length())) {
            errorMessages.add("名前は20文字以下で入力してください");
        }
        if (StringUtils.isEmpty(account)) {
            errorMessages.add("アカウント名を入力してください");
        } else if (20 < account.length()) {
            errorMessages.add("アカウント名は20文字以下で入力してください");

        } else if ((accountMatchUser != null) && (accountMatchUser.getId() != id)) {
        	errorMessages.add("そのアカウント名は既に使われています");
        }

        if (!StringUtils.isEmpty(email) && (50 < email.length())) {
            errorMessages.add("メールアドレスは50文字以下で入力してください");
        }

        if (errorMessages.size() != 0) {
            return false;
        }
        return true;
    }
}

src/chapter6/controller/SignUpServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        request.getRequestDispatcher("signup.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        List<String> errorMessages = new ArrayList<String>();
        User user = getUser(request);
        if (!isValid(user, errorMessages)) {
            request.setAttribute("errorMessages", errorMessages);
            request.setAttribute("user", user);//値の保持
            request.getRequestDispatcher("signup.jsp").forward(request, response);
            return;
        }

        new UserService().insert(user);

        response.sendRedirect("./");
    }

    private User getUser(HttpServletRequest request) throws IOException, ServletException {
        User user = new User();
        user.setName(request.getParameter("name"));
        user.setAccount(request.getParameter("account"));
        user.setPassword(request.getParameter("password"));
        user.setEmail(request.getParameter("email"));
        user.setDescription(request.getParameter("description"));
        return user;
    }

    private boolean isValid(User user, List<String> errorMessages) {

    	String name = user.getName();
        String account = user.getAccount();
        String password = user.getPassword();
        String email = user.getEmail();
        User accountMatchUser = new UserService().select(account);

        if (!StringUtils.isEmpty(name) && (20 < name.length())) {
            errorMessages.add("名前は20文字以下で入力してください");
        }

        if (StringUtils.isEmpty(account)) {
            errorMessages.add("アカウント名を入力してください");
        } else if (20 < account.length()) {
            errorMessages.add("アカウント名は20文字以下で入力してください");
        } else if(accountMatchUser != null) {
        	errorMessages.add("そのアカウント名は既に使われています");
        }

        if (StringUtils.isEmpty(password)) {
            errorMessages.add("パスワードを入力してください");
        }

        if (!StringUtils.isEmpty(email) && (50 < email.length())) {
            errorMessages.add("メールアドレスは50文字以下で入力してください");
        }

        if (errorMessages.size() != 0) {
            return false;
        }
        return true;
    }
}

src/chapter6/controller/TopServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import chapter6.beans.User;
import chapter6.beans.UserComment;
import chapter6.beans.UserMessage;
import chapter6.service.CommentService;
import chapter6.service.MessageService;

@WebServlet(urlPatterns = { "/index.jsp" })
public class TopServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        boolean isShowMessageForm = false;//comment入力欄も子の変数名で統一
        User user = (User) request.getSession().getAttribute("loginUser");

        if (user != null) {
            isShowMessageForm = true;
        }

        String userId = request.getParameter("user_id");
        String start = request.getParameter("startDate");
        String end = request.getParameter("endDate");

        List<UserMessage> messages = new MessageService().select(userId, start, end);

        request.setAttribute("messages", messages);
        request.setAttribute("startDate", start);
        request.setAttribute("endDate", end);

        List<UserComment> comments = new CommentService().select();

        request.setAttribute("comments", comments);
        request.setAttribute("isShowMessageForm", isShowMessageForm);
        request.getRequestDispatcher("/top.jsp").forward(request, response);
    }
}

WebContent/edit.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>つぶやきの編集</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>

	<body>
		<div class="main-contents">
			<c:if test="${ not empty errorMessages }">
				<div class="errorMessages">
					<ul>
						<c:forEach items="${errorMessages}" var="errorMessage">
							<li><c:out value="${errorMessage}" />
						</c:forEach>
					</ul>
				</div>
			</c:if>
			<br>
			<div class="edit-area">
				 <form action="edit" method="post">
					<input name ="id" value="${message.id}" id = "id"  type= "hidden"/>
					<label for = "text">編集</label>
					<textarea name="text" cols="95" rows="5" id="text"><c:out value="${message.text}"/></textarea>
					<br>
					<input type="submit" value="更新">（140文字まで）
					<br>
					<a href="./">戻る</a>
				</form>
			</div>
			<div class="copyright"> Copyright(c)ShinichiroYoshida.com</div>
		</div>
	</body>
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>ログイン</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>

	<body>
		<div class="main-contents">
			<c:if test="${ not empty errorMessages }">
				<div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

            <form action="login" method="post"><br />
                <label for="accountOrEmail">アカウント名かメールアドレス</label>
                <input name="accountOrEmail" id="accountOrEmail"/> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                <input type="submit" value="ログイン" /> <br />
                <a href="./">戻る</a>
            </form>
            <div class="copyright"> Copyright(c)ShinichiroYoshida.com</div>
        </div>
    </body>
</html>

WebContent/setting.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>${loginUser.account}の設定</title>
        <link href="css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">
            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

            <form action="setting" method="post">
            	<br />
                <input name="id" value="${user.id}" id="id" />

                <label for="name">名前</label>
                <input name="name" value="${user.name}" id="name"/>（名前はあなたの公開プロフィールに表示されます）<br />

                <label for="account">アカウント名</label>
                <input name="account" value="${user.account}" /><br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> (入力しない場合、パスワードは更新されません) <br />

                <label for="email">メールアドレス</label>
                <input name="email" value="${user.email}" id="email"/> <br />

                <label for="description">説明</label>
                <textarea name="description" cols="35" rows="5" id="description"><c:out value="${user.description}" /></textarea> <br />

                <input type="submit" value="更新" /> <br />
                <a href="./">戻る</a>
            </form>
            <div class="copyright"> Copyright(c)ShinichiroYoshida.com</div>
        </div>
    </body>
</html>

WebContent/signup.jsp
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	    <title>ユーザー登録</title>
	    <link href="./css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">
            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

            <form action="signup" method="post"><br />
                <label for="name">名前</label>
                <input name="name" value="${user.name}" id="name" />（名前はあなたの公開プロフィールに表示されます）<br />

                <label for="account">アカウント名</label>
                <input name="account" value="${user.account}" id="account" /><br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password" /><br />

                <label for="email">メールアドレス</label>
                <input name="email" value="${user.email}" id="email" /><br />

                <label for="description">説明</label>
                <textarea name="description" cols="35" rows="5" id="description"><c:out value="${user.description}" />
                </textarea><br />
                <input type="submit" value="登録" /><br />
                <a href="./">戻る</a>
            </form>
            <div class="copyright">Copyright(c)ShinichiroYoshida.com</div>
        </div>
    </body>
</html>

WebContent/top.jsp
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
	<!-- HTMLのどのバージョン (種類)に準拠したものなのかを示す目的で使用 -->
	<!-- HTML5では文書型宣言は文法的には不要 -->
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>簡易Twitter</title>
        <link href="./css/style.css" rel="stylesheet" type="text/css">
        <script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
		<script>
			$(function() {
				$('#delete').on('click', function() {
					alert('消去してよろしいでしょうか');
				});
			});
		</script>
    </head>

    <body>
        <div class="main-contents">
            <div class="header">
			    <c:if test="${ empty loginUser }">
			        <a href="login">ログイン</a>
			        <a href="signup">登録する</a>
			    </c:if>

			    <c:if test="${ not empty loginUser }">
			        <a href="./">ホーム</a>
			        <a href="setting">設定</a>
			        <a href="logout">ログアウト</a>
			    </c:if>
			</div>

			<div class="narrowDown-function">
				<form action = "./" method = "get">
					<input type = "date" name = "startDate" value = "${startDate}" min = "2020-01-01">
					～
					<input type = "date" name = "endDate" value = "${endDate}"><br>
					<input type = "submit" value = "絞込">
				</form>
			</div>

		    <div class="profile">
				<c:if test="${ not empty loginUser }">
			        <div class="name">
			        	<h2>
			        		<c:out value="${loginUser.name}" />
			        	</h2>
			        </div>

			        <div class="account">
			        	@<c:out value="${loginUser.account}" />
			        </div>

			        <div class="description">
			        	<c:out value="${loginUser.description}" />
			        </div>
				</c:if>
		    </div>

		    <div class="errorMessages">
				<c:if test="${ not empty errorMessages }">
			        <ul>
			            <c:forEach items="${errorMessages}" var="errorMessage">
			            <li><c:out value="${errorMessage}" />
			            </c:forEach>
			        </ul>
			    	<c:remove var="errorMessages" scope="session" />
				</c:if>
		    </div>

			<div class="form-area">
			    <c:if test="${ isShowMessageForm }">
			        <form action="message" method="post">
			            いま、どうしてる？<br />
			            <textarea name="text" cols="100" rows="5" class="tweet-box"></textarea><br />
			            <input type="submit" value="つぶやく">（140文字まで）<br>
			        </form>
			    </c:if>
			</div>
			<br>
			<div class="messages">
			    <c:forEach items="${messages}" var="message">
			        <div class="message">
			           <div class="account-name">
			                <span class="account">
			            		<a href="./?user_id=<c:out value="${message.userId}"/> ">
			            			<c:out value="${message.account}" />
			                	</a>
			                </span>

			            	<span class="name">
			            		<c:out value="${message.name}" />
			            	</span>
			            </div>

						<c:forEach var="s" items="${fn:split(message.text, '
')}">
				            <div class="text">
				            	<c:out value="${s}" />
				            </div>
			            </c:forEach>

			            <div class="date">
			            	<fmt:formatDate value="${message.created_Date}" pattern="yyyy/MM/dd HH:mm:ss" />
			            </div>

						<div class = "edit-reply">
							<c:if test="${ loginUser.account == message.account }">
								<div class = "edit">
									<form action = "edit" method = "get">
										<input name = "messageId" value = "${message.id}" type= "hidden"><br>
					        			<input type="submit"  value ="編集"/>
					        		</form>
				        		</div>

				        		<div class = "delete">
					        		<form action = "deleteMessage" method = "post">
					        			<input name="messageId" value="${message.id}" type="hidden">
					        			<input type="submit" value="消去" id="delete"/><br><br>
					        		</form>
					        	</div>
							</c:if>
						</div>

			        	<div class = "comments">
			        		<c:forEach items = "${comments}" var = "comment">
								<c:if test="${ message.id == comment.messageId }">
									<div class = "account-name">
										<span class = "account">
											<c:out value = "${comment.account}"/>
										</span>

										<span class = "name">
											<c:out value = "${comment.name}"/>
										</span>
									</div>

									<c:forEach var="r" items="${fn:split(comment.text, '
')}">
										<div class = "text">
											<c:out value = "${r}"/>
										</div>
									</c:forEach>

									<div class = "date">
										<fmt:formatDate value = "${comment.created_Date}"  pattern = "yyy/MM/dd HH:mm:ss"/>
									</div>
								</c:if>
							</c:forEach>
						</div>

						<div class = "commentform-area">
							<c:if test = "${ isShowMessageForm }">
								<div class = "comment">
									<form action = "comment" method = "post">
										<input name = "messageId" value = "${message.id}" type= "hidden"><br>
										返信<br>
										<textarea name = "comment" cols="90" rows="5" class="comment-box"></textarea><br>
										<input type = "submit" value = "返信"><br><br><br>
									</form>
				        		</div>
			        		</c:if>
			       		</div>
			       </div>
			    </c:forEach>
			</div>
            <div class="copyright"> Copyright(c)ShinichiroYoshida.com</div>
        </div>
    </body>
</html>